{% set version = "3.8.2" %}

package:
  name: djangorestframework
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/djangorestframework/djangorestframework-{{ version }}.tar.gz
  sha256: b6714c3e4b0f8d524f193c91ecf5f5450092c2145439ac2769711f7eba89a9d9

build:
  number: 0
  noarch: python

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - rest_framework
    - rest_framework.authtoken
    - rest_framework.authtoken.migrations
    - rest_framework.templatetags
    - rest_framework.utils

outputs:
  - name: djangorestframework
    build:
      script: python -m pip install --no-deps --ignore-installed .
    requirements:
      - python
      - django

  - name: django-rest-framework
    requirements:
      - python
      - {{ pin_subpackage('djangorestframework', exact=True) }}

about:
  home: http://www.django-rest-framework.org
  license: BSD 2-Clause
  summary: 'Web APIs for Django, made easy'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
    - scopatz
