{% set name = "djangorestframework" %}
{% set version = "3.16.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/djangorestframework-{{ version }}.tar.gz
  sha256: 166809528b1aced0a17dc66c24492af18049f2c9420dbd0be29422029cfc3ff7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - django >=4.2

test:
  imports:
    - rest_framework
    - rest_framework.authtoken
    - rest_framework.authtoken.migrations
    - rest_framework.templatetags
    - rest_framework.utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.django-rest-framework.org/
  summary: Web APIs for Django, made easy.
  dev_url: https://github.com/encode/django-rest-framework
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
